import { getAllMatches } from "@/mockapi/matchApi";
import Head from "next/head";
import { useContext, useEffect, useState } from "react";
import { MatchList } from "../MatchList/MatchList";
import { UserList } from "../UserList/UserList";
import styles from "./DisplayScreen.module.css";
import { IMatch } from "@/src/interfaces/match";
import { DisplayScreen__Chessboard } from "./DisplayScreen__Chessboard";
import { getBoardStanding } from "@/mockapi/boardstandingApi";
import { TwitterFeed } from "../TwitterFeed/TwitterFeed";
import AuthContext from "@/stores/authContext";
import { useQuery } from "react-query";
import Image from "next/image";

export const DisplayScreen = () => {
  //const { standing } = getBoardStanding();
  const { users } = useContext(AuthContext);

  const {
    isLoading: matchLoading,
    error,
    data: matches,
  } = useQuery("matchData", () =>
    fetch("https://nrk-chess-api.onrender.com/match/all").then((res) =>
      res.json()
    )
  );

  const { isLoading: standingLoading, data: standingData } = useQuery(
    "standingData",
    () =>
      fetch("https://nrk-chess-api.onrender.com/chess_display").then((res) =>
        res.json()
      )
  );

  const { isLoading: funFactLoading, data: funFactData } = useQuery(
    "funFact",
    () =>
      fetch("https://nrk-chess-api.onrender.com/fun_fact/chess").then((res) =>
        res.json()
      )
  );

  return (
    <>
      <Head>
        <title>Nordland Chess</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/chess-board-logo.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.leftSide}>
          <div className={styles.qrCodeBox}>
            <div className={styles.qrCodeBoxTitle}>
              <h3>Besøk siden</h3>
            </div>
            <div className={styles.qrCode}>
              <Image
                className={styles.qrCodeImage}
                src="/qr-code.png"
                alt="qr-code"
                width={500}
                height={500}
              />
            </div>
          </div>
          <div className={styles.twitterFeedContainer}>
            <TwitterFeed />
          </div>
        </div>
        <div className={styles.middle}>
          {users != null && <UserList users={users} />}
          {matchLoading === false && matches != null && (
            <div className={styles.matchListContainer}>
              <MatchList matches={matches} />
            </div>
          )}
        </div>
        <div className={styles.rightSide}>
          <div className={styles.chessBoardContainer}>
            {standingLoading === false && standingData != null && (
              <DisplayScreen__Chessboard standing={standingData.standing} />
            )}
          </div>
          {funFactLoading === false && funFactData != null && (
            <div className={styles.funfactBox}>
              <div className={styles.funfactBoxTitle}>
                <h3>Fun Fact</h3>
              </div>
              <span className={styles.funfactBoxText}>
                {funFactData.funFact}
              </span>
            </div>
          )}
          <div className={styles.houseRulesBox}>
            <div className={styles.houseRulesBoxTitle}>
              <h3>Husregler</h3>
            </div>
            <ul className={styles.houseRulesList}>
              <li className={styles.houseRule}>
                <span className={styles.houseRulesPoint}>♛</span>
                <span className={styles.houseRulesText}>
                  Spilleformat: 3+2 blitz.
                </span>
              </li>
              <li className={styles.houseRule}>
                <span className={styles.houseRulesPoint}>♜</span>
                <span className={styles.houseRulesText}>
                  Taper av siste inbyrdes parti er hvit. Har man ikke møttes
                  tidligere avgjøres det av spillerenes rating.
                </span>
              </li>
              <li className={styles.houseRule}>
                <span className={styles.houseRulesPoint}>♞</span>
                <span className={styles.houseRulesText}>
                  Har du ikke spilt sjakk i dag kan du ikke avslå en udfordring.
                </span>
              </li>
            </ul>
          </div>
        </div>
      </main>
    </>
  );
};
