import { getAllMatches } from "@/mockapi/matchApi";
import Head from "next/head";
import { useContext, useEffect, useState } from "react";
import { MatchList } from "../MatchList/MatchList";
import { UserList } from "../UserList/UserList";
import styles from "./DisplayScreen.module.css";
import { IMatch } from "@/src/interfaces/match";
import { DisplayScreen__Chessboard } from "./DisplayScreen__Chessboard";
import { getBoardStanding } from "@/mockapi/boardstandingApi";
import { TwitterFeed } from "../TwitterFeed/TwitterFeed";
import AuthContext from "@/stores/authContext";
import { useQuery } from "react-query";

export const DisplayScreen = () => {
  //const { standing } = getBoardStanding();
  const { users } = useContext(AuthContext);

  const {
    isLoading: matchLoading,
    error,
    data: matches,
  } = useQuery("matchData", () =>
    fetch(
      "http://ec2-16-171-34-21.eu-north-1.compute.amazonaws.com/match/all"
    ).then((res) => res.json())
  );

  const { isLoading: standingLoading, data: standingData } = useQuery(
    "standingData",
    () =>
      fetch(
        "http://ec2-16-171-34-21.eu-north-1.compute.amazonaws.com/chess_display"
      ).then((res) => res.json())
  );

  return (
    <>
      <Head>
        <title>Nordland Chess</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/chess-board-logo.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.leftSide}>
          <div className={styles.twitterFeedContainer}>
            <TwitterFeed />
          </div>
        </div>
        <div className={styles.middle}>
          {users != null && <UserList users={users} />}
          {matchLoading === false && matches != null && (
            <MatchList matches={matches} />
          )}
        </div>
        <div className={styles.rightSide}>
          <div className={styles.chessBoardContainer}>
            {standingLoading === false && standingData != null && (
              <DisplayScreen__Chessboard standing={standingData.standing} />
            )}
          </div>
        </div>
      </main>
    </>
  );
};
